### PR TITLE
Ruby 2.3

### PR DESCRIPTION
**Pull request by marcinsklodowski**

### CODE REVIEW

**Comment by michaelw90** [comment]
You need to update the version within the metadata.rb file as well.

**Comment by marcinsklodowski** [comment]
updated!

**Comment by michaelw90** [comment]
@marcinsklodowski I'm assuming this will mean we need to update the version of Ruby on the Build Agents?

**Comment by marcinsklodowski** [comment]
@michaelw90 yes, we need updated Ruby version when we run rspecs

**Pull request merged**
